# Generated by Django 2.2.3 on 2019-07-18 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
